import datetime

from PyQt5 import QtCore, QtGui, QtWidgets
# 回测模块前端


class Ui_TradingStockBacktestWindow(object):
    def setupUi(self, TradingStockBacktestWindow):
        TradingStockBacktestWindow.setObjectName("TradingStockBacktestWindow")
        TradingStockBacktestWindow.resize(1148, 769)
        TradingStockBacktestWindow.setToolTip("")
        TradingStockBacktestWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(TradingStockBacktestWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidgetBacktest = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetBacktest.setGeometry(QtCore.QRect(10, 350, 1131, 431))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidgetBacktest.setFont(font)
        self.tableWidgetBacktest.setColumnCount(7)
        self.tableWidgetBacktest.setObjectName("tableWidgetBacktest")
        self.tableWidgetBacktest.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBacktest.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBacktest.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBacktest.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBacktest.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBacktest.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBacktest.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBacktest.setHorizontalHeaderItem(6, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidgetBacktest.setHorizontalHeaderItem(7, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidgetBacktest.setHorizontalHeaderItem(8, item)
        self.tableWidgetBacktest.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetBacktest.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetBacktest.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetBacktest.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidgetBacktest.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetBacktest.verticalHeader().setStretchLastSection(False)
        self.tableWidgetBaseInfo = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetBaseInfo.setGeometry(QtCore.QRect(10, 170, 1131, 131))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidgetBaseInfo.setFont(font)
        self.tableWidgetBaseInfo.setColumnCount(7)
        self.tableWidgetBaseInfo.setObjectName("tableWidgetBaseInfo")
        self.tableWidgetBaseInfo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBaseInfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBaseInfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBaseInfo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBaseInfo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBaseInfo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBaseInfo.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBaseInfo.setHorizontalHeaderItem(6, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidgetBaseInfo.setHorizontalHeaderItem(7, item)
        self.tableWidgetBaseInfo.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetBaseInfo.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetBaseInfo.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetBaseInfo.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidgetBaseInfo.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetBaseInfo.verticalHeader().setStretchLastSection(False)
        self.pushButtonOk = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOk.setGeometry(QtCore.QRect(950, 40, 131, 32))
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 320, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 500, 34))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stocklabel = QtWidgets.QLabel(self.layoutWidget)
        self.stocklabel.setObjectName("stocklabel")
        self.horizontalLayout.addWidget(self.stocklabel)
        self.lineEditStockcode = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditStockcode.setObjectName("lineEditStockcode")
        self.horizontalLayout.addWidget(self.lineEditStockcode)
        self.pushButton30day = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton30day.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton30day.setStyleSheet("")
        self.pushButton30day.setObjectName("pushButton30day")
        self.horizontalLayout.addWidget(self.pushButton30day)
        self.pushButton60day = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton60day.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton60day.setStyleSheet("")
        self.pushButton60day.setObjectName("pushButton60day")
        self.horizontalLayout.addWidget(self.pushButton60day)
        self.pushButton120day = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton120day.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton120day.setStyleSheet("")
        self.pushButton120day.setObjectName("pushButton120day")
        self.horizontalLayout.addWidget(self.pushButton120day)
        self.pushButton240day = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton240day.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton240day.setStyleSheet("")
        self.pushButton240day.setObjectName("pushButton240day")
        self.horizontalLayout.addWidget(self.pushButton240day)

        # 自定义时间
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(630, 0, 511, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBoxSelfTime = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBoxSelfTime.setObjectName("checkBoxSelfTime")
        self.horizontalLayout_2.addWidget(self.checkBoxSelfTime)
        self.lineEditTimeStart = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditTimeStart.setObjectName("lineEditTimeStart")
        self.horizontalLayout_2.addWidget(self.lineEditTimeStart)
        self.lineEditTimeEnd = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditTimeEnd.setObjectName("lineEditTimeEnd")
        self.horizontalLayout_2.addWidget(self.lineEditTimeEnd)

        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 41, 721, 28))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEditMACD = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditMACD.setObjectName("lineEditMACD")
        self.horizontalLayout_3.addWidget(self.lineEditMACD)
        self.checkBoxStop = QtWidgets.QLabel(self.layoutWidget2)
        self.checkBoxStop.setObjectName("checkBoxStop")
        self.horizontalLayout_3.addWidget(self.checkBoxStop)
        self.lineEditStop = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditStop.setObjectName("lineEditStop")
        self.horizontalLayout_3.addWidget(self.lineEditStop)
        self.checkBoxAdd = QtWidgets.QCheckBox(self.layoutWidget2)
        self.checkBoxAdd.setMinimumSize(QtCore.QSize(250, 0))
        self.checkBoxAdd.setMaximumSize(QtCore.QSize(150, 16777215))
        self.checkBoxAdd.setObjectName("checkBoxAdd")
        self.horizontalLayout_3.addWidget(self.checkBoxAdd)
        # 策略选择
        self.rbtn1 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.rbtn2 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.selectType = QtWidgets.QButtonGroup(self.layoutWidget2)
        self.selectType.setObjectName("selectTpye")
        self.selectType.addButton(self.rbtn1)
        self.selectType.addButton(self.rbtn2)
        self.horizontalLayout_3.addWidget(self.rbtn1)
        self.horizontalLayout_3.addWidget(self.rbtn2)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(11, 80, 511, 31))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.setPrincipal = QtWidgets.QLabel(self.layoutWidget3)
        self.setPrincipal.setObjectName("checkCharge")
        self.horizontalLayout_4.addWidget(self.setPrincipal)
        self.linePrincipal = QtWidgets.QLineEdit(self.layoutWidget3)
        self.linePrincipal.setObjectName("linePrincipal")
        self.horizontalLayout_4.addWidget(self.linePrincipal)
        self.checkCharge = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkCharge.setObjectName("checkCharge")
        self.checkCharge.setMinimumSize(QtCore.QSize(250, 10))
        self.horizontalLayout_4.addWidget(self.checkCharge)
        # 显示选中的时间
        self.label_TimeStatus = QtWidgets.QLabel(self.centralwidget)
        self.label_TimeStatus.setGeometry(QtCore.QRect(580, 0, 70, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_TimeStatus.setFont(font)
        self.label_TimeStatus.setText("")
        self.label_TimeStatus.setAlignment(QtCore.Qt.AlignLeft)
        self.label_TimeStatus.setObjectName("label_TimeStatus")
        TradingStockBacktestWindow.setCentralWidget(self.centralwidget)
        self.pushButtonReturn = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonReturn.setGeometry(QtCore.QRect(800, 40, 131, 32))
        self.pushButtonReturn.setObjectName("pushButtonReturn")
        self.retranslateUi(TradingStockBacktestWindow)

        QtCore.QMetaObject.connectSlotsByName(TradingStockBacktestWindow)




    def retranslateUi(self, TradingStockBacktestWindow):
        _translate = QtCore.QCoreApplication.translate
        TradingStockBacktestWindow.setWindowTitle(_translate("TradingStockBacktestWindow", "股票交易-单日交易模拟回测"))
        item = self.tableWidgetBacktest.horizontalHeaderItem(0)
        item.setText(_translate("TradingStockBacktestWindow", "交易日期"))
        item = self.tableWidgetBacktest.horizontalHeaderItem(1)
        item.setText(_translate("TradingStockBacktestWindow", "股票代码"))
        item = self.tableWidgetBacktest.horizontalHeaderItem(2)
        item.setText(_translate("TradingStockBacktestWindow", "股票名称"))
        item = self.tableWidgetBacktest.horizontalHeaderItem(3)
        item.setText(_translate("TradingStockBacktestWindow", "交易类型"))
        item = self.tableWidgetBacktest.horizontalHeaderItem(4)
        item.setText(_translate("TradingStockBacktestWindow", "成交价格"))
        item = self.tableWidgetBacktest.horizontalHeaderItem(5)
        item.setText(_translate("TradingStockBacktestWindow", "成交数量"))
        item = self.tableWidgetBacktest.horizontalHeaderItem(6)
        item.setText(_translate("TradingStockBacktestWindow", "总资产"))
        item = self.tableWidgetBaseInfo.horizontalHeaderItem(0)
        item.setText(_translate("TradingStockBacktestWindow", "股票名称"))
        item = self.tableWidgetBaseInfo.horizontalHeaderItem(1)
        item.setText(_translate("TradingStockBacktestWindow", "股票代码"))
        item = self.tableWidgetBaseInfo.horizontalHeaderItem(2)
        item.setText(_translate("TradingStockBacktestWindow", "期间股票涨幅"))
        item = self.tableWidgetBaseInfo.horizontalHeaderItem(3)
        item.setText(_translate("TradingStockBacktestWindow", "期间策略收益率"))
        item = self.tableWidgetBaseInfo.horizontalHeaderItem(4)
        item.setText(_translate("TradingStockBacktestWindow", "年化收益率"))
        item = self.tableWidgetBaseInfo.horizontalHeaderItem(5)
        item.setText(_translate("TradingStockBacktestWindow", "夏普比率"))
        item = self.tableWidgetBaseInfo.horizontalHeaderItem(6)
        item.setText(_translate("TradingStockBacktestWindow", "最大回撤率"))
        self.pushButtonOk.setText(_translate("TradingStockBacktestWindow", "确定"))
        self.label_2.setText(_translate("TradingStockBacktestWindow", "股票基本信息"))
        self.label_3.setText(_translate("TradingStockBacktestWindow", "股票回测成交记录"))
        self.pushButton30day.setText(_translate("TradingStockBacktestWindow", "30天"))
        self.pushButton60day.setText(_translate("TradingStockBacktestWindow", "60天"))
        self.pushButton120day.setText(_translate("TradingStockBacktestWindow", "120天"))
        self.pushButton240day.setText(_translate("TradingStockBacktestWindow", "240天"))
        self.checkBoxSelfTime.setText(_translate("TradingStockBacktestWindow", "自定义时间"))
        curr_time = datetime.datetime.now()
        time_str = curr_time.strftime("%Y%m%d")
        curr_time = curr_time + datetime.timedelta(days=-30)
        self.lineEditTimeStart.setText(curr_time.strftime("%Y%m%d"))
        self.lineEditTimeEnd.setText(time_str)
        self.stocklabel.setText(_translate("TradingStockBacktestWindow", "股票代码"))
        self.lineEditStockcode.setText("603906.SH")
        self.label.setText(_translate("TradingStockBacktestWindow", "MACD/RSI变化率"))
        self.lineEditMACD.setText("0.5")
        self.checkBoxStop.setText(_translate("TradingStockBacktestWindow", "强制止损"))
        self.lineEditStop.setText("100")
        self.checkBoxAdd.setText(_translate("TradingStockBacktestWindow", "允许加仓"))
        self.rbtn1.setText(_translate("TradingStockBacktestWindow", "策略一"))
        self.rbtn1.setChecked(True)
        self.rbtn2.setText(_translate("TradingStockBacktestWindow", "策略二"))
        self.setPrincipal.setText(_translate("TradingStockBacktestWindow", "初始本金"))
        self.linePrincipal.setText("100000")
        self.checkCharge.setText(_translate("TradingStockBacktestWindow", "是否计算手续费"))
        self.pushButtonReturn.setText(_translate("TradingStockBacktestWindow","返回主界面"))
        self.label_TimeStatus.setText("30天")