from PyQt5 import QtCore, QtGui, QtWidgets
# 交易推荐模块前端


class Ui_TradingSuggestWindow(object):
    def setupUi(self, TradingSuggestWindow):
        TradingSuggestWindow.setObjectName("TradingStockBacktestWindow")
        TradingSuggestWindow.resize(1148, 769)
        TradingSuggestWindow.setToolTip("")
        TradingSuggestWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(TradingSuggestWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidgetBacktest = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetBacktest.setGeometry(QtCore.QRect(10, 300, 1131, 431))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidgetBacktest.setFont(font)
        self.tableWidgetBacktest.setColumnCount(6)
        self.tableWidgetBacktest.setObjectName("tableWidgetBacktest")
        self.tableWidgetBacktest.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBacktest.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBacktest.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBacktest.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBacktest.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBacktest.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBacktest.setHorizontalHeaderItem(5, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidgetBacktest.setHorizontalHeaderItem(6, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidgetBacktest.setHorizontalHeaderItem(7, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidgetBacktest.setHorizontalHeaderItem(8, item)
        self.tableWidgetBacktest.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetBacktest.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetBacktest.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetBacktest.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidgetBacktest.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetBacktest.verticalHeader().setStretchLastSection(False)
        self.tableWidgetBaseInfo = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetBaseInfo.setGeometry(QtCore.QRect(10, 110, 1131, 131))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidgetBaseInfo.setFont(font)
        self.tableWidgetBaseInfo.setColumnCount(6)
        self.tableWidgetBaseInfo.setObjectName("tableWidgetBaseInfo")
        self.tableWidgetBaseInfo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBaseInfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBaseInfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBaseInfo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBaseInfo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBaseInfo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBaseInfo.setHorizontalHeaderItem(5, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidgetBaseInfo.setHorizontalHeaderItem(6, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidgetBaseInfo.setHorizontalHeaderItem(7, item)
        self.tableWidgetBaseInfo.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetBaseInfo.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetBaseInfo.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetBaseInfo.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidgetBaseInfo.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetBaseInfo.verticalHeader().setStretchLastSection(False)
        self.pushButtonOk = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOk.setGeometry(QtCore.QRect(950, 40, 131, 32))
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 270, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 500, 34))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stocklabel = QtWidgets.QLabel(self.layoutWidget)
        self.stocklabel.setObjectName("stocklabel")
        self.horizontalLayout.addWidget(self.stocklabel)
        self.lineEditStockcode = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditStockcode.setObjectName("lineEditStockcode")
        self.lineEditStockcode.setText("603906.SH")
        self.horizontalLayout.addWidget(self.lineEditStockcode)
        # 策略选择
        self.rbtn1 = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtn2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.selectType = QtWidgets.QButtonGroup(self.layoutWidget)
        self.selectType.setObjectName("selectTpye")
        self.selectType.addButton(self.rbtn1)
        self.selectType.addButton(self.rbtn2)
        self.horizontalLayout.addWidget(self.rbtn1)
        self.horizontalLayout.addWidget(self.rbtn2)

        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(630, 0, 511, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.suggest = QtWidgets.QLabel(self.layoutWidget1)
        self.suggest.setObjectName("suggest")
        self.horizontalLayout_2.addWidget(self.suggest)

        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 41, 721, 28))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEditMACD = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditMACD.setObjectName("lineEditMACD")
        self.lineEditMACD.setText("0.5")
        # self.lineEditMACD.setMaximumSize(QtCore.QSize(250, 40))
        self.horizontalLayout_3.addWidget(self.lineEditMACD)

        # 显示看多看空
        self.trade_type = QtWidgets.QLabel(self.centralwidget)
        self.trade_type.setGeometry(QtCore.QRect(800, 0, 150, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.trade_type.setFont(font)
        self.trade_type.setText("")
        self.trade_type.setAlignment(QtCore.Qt.AlignLeft)
        self.trade_type.setObjectName("label_TimeStatus")

        self.pushButtonReturn = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonReturn.setGeometry(QtCore.QRect(800, 40, 131, 32))
        self.pushButtonReturn.setObjectName("pushButtonReturn")

        TradingSuggestWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TradingSuggestWindow)
        QtCore.QMetaObject.connectSlotsByName(TradingSuggestWindow)

    def retranslateUi(self, TradingStockBacktestWindow):
        _translate = QtCore.QCoreApplication.translate
        TradingStockBacktestWindow.setWindowTitle(_translate("TradingStockBacktestWindow", "股票交易-实时交易"))
        item = self.tableWidgetBacktest.horizontalHeaderItem(0)
        item.setText(_translate("TradingStockBacktestWindow", "股票名称"))
        item = self.tableWidgetBacktest.horizontalHeaderItem(1)
        item.setText(_translate("TradingStockBacktestWindow", "股票代码"))
        item = self.tableWidgetBacktest.horizontalHeaderItem(2)
        item.setText(_translate("TradingStockBacktestWindow", "当前股价"))
        item = self.tableWidgetBacktest.horizontalHeaderItem(3)
        item.setText(_translate("TradingStockBacktestWindow", "开盘价"))
        item = self.tableWidgetBacktest.horizontalHeaderItem(4)
        item.setText(_translate("TradingStockBacktestWindow", "最高价"))
        item = self.tableWidgetBacktest.horizontalHeaderItem(5)
        item.setText(_translate("TradingStockBacktestWindow", "最低价"))
        # item = self.tableWidgetBacktest.horizontalHeaderItem(6)
        # item.setText(_translate("TradingStockBacktestWindow", "换手率"))
        item = self.tableWidgetBaseInfo.horizontalHeaderItem(0)
        item.setText(_translate("TradingStockBacktestWindow", "股票名称"))
        item = self.tableWidgetBaseInfo.horizontalHeaderItem(1)
        item.setText(_translate("TradingStockBacktestWindow", "股票代码"))
        item = self.tableWidgetBaseInfo.horizontalHeaderItem(2)
        item.setText(_translate("TradingStockBacktestWindow", "当前股价"))
        item = self.tableWidgetBaseInfo.horizontalHeaderItem(3)
        item.setText(_translate("TradingStockBacktestWindow", "开盘价"))
        item = self.tableWidgetBaseInfo.horizontalHeaderItem(4)
        item.setText(_translate("TradingStockBacktestWindow", "最高价"))
        item = self.tableWidgetBaseInfo.horizontalHeaderItem(5)
        item.setText(_translate("TradingStockBacktestWindow", "最低价"))
        # item = self.tableWidgetBaseInfo.horizontalHeaderItem(6)
        # item.setText(_translate("TradingStockBacktestWindow", "换手率"))
        # item = self.tableWidgetBaseInfo.horizontalHeaderItem(7)
        # item.setText(_translate("TradingStockBacktestWindow", "总分"))
        self.pushButtonOk.setText(_translate("TradingStockBacktestWindow", "刷新"))
        self.label_2.setText(_translate("TradingStockBacktestWindow", "股票基本信息"))
        self.label_3.setText(_translate("TradingStockBacktestWindow", "当前策略推荐股票"))
        self.label.setText(_translate("TradingStockBacktestWindow", "MACD/RSI变化率"))
        self.suggest.setText(_translate("TradingStockBacktestWindow", "推荐交易类型"))
        self.stocklabel.setText(_translate("TradingStockBacktestWindow", "股票代码"))
        self.rbtn1.setText(_translate("TradingStockBacktestWindow", "策略一"))
        self.rbtn1.setChecked(True)
        self.rbtn2.setText(_translate("TradingStockBacktestWindow", "策略二"))
        self.pushButtonReturn.setText(_translate("TradingStockBacktestWindow","返回主界面"))