from PyQt5 import QtCore, QtGui, QtWidgets
# 交易推荐模块前端


class Ui_TradingSuggestStockWindow(object):
    def setupUi(self, TradingSuggestStockWindow):
        TradingSuggestStockWindow.setObjectName("TradingSuggestStockWindow")
        TradingSuggestStockWindow.resize(1148, 769)
        TradingSuggestStockWindow.setToolTip("")
        TradingSuggestStockWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(TradingSuggestStockWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidgetBacktest = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetBacktest.setGeometry(QtCore.QRect(10, 100, 1131, 631))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidgetBacktest.setFont(font)
        self.tableWidgetBacktest.setColumnCount(6)
        self.tableWidgetBacktest.setObjectName("tableWidgetBacktest")
        self.tableWidgetBacktest.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBacktest.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBacktest.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBacktest.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBacktest.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBacktest.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBacktest.setHorizontalHeaderItem(5, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidgetBacktest.setHorizontalHeaderItem(6, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidgetBacktest.setHorizontalHeaderItem(7, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidgetBacktest.setHorizontalHeaderItem(8, item)
        self.tableWidgetBacktest.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetBacktest.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetBacktest.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetBacktest.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidgetBacktest.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetBacktest.verticalHeader().setStretchLastSection(False)

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)

        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 500, 34))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        # 策略选择
        self.rbtn1 = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtn2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbtn3 = QtWidgets.QRadioButton(self.layoutWidget)
        self.selectType = QtWidgets.QButtonGroup(self.layoutWidget)
        self.selectType.setObjectName("selectTpye")
        self.selectType.addButton(self.rbtn1)
        self.selectType.addButton(self.rbtn2)
        self.selectType.addButton(self.rbtn3)
        self.horizontalLayout.addWidget(self.rbtn1)
        self.horizontalLayout.addWidget(self.rbtn2)
        self.horizontalLayout.addWidget(self.rbtn3)

        self.pushButtonReturn = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonReturn.setGeometry(QtCore.QRect(800, 40, 131, 32))
        self.pushButtonReturn.setObjectName("pushButtonReturn")

        TradingSuggestStockWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(TradingSuggestStockWindow)
        QtCore.QMetaObject.connectSlotsByName(TradingSuggestStockWindow)

    def retranslateUi(self, TradingStockBacktestWindow):
        _translate = QtCore.QCoreApplication.translate
        TradingStockBacktestWindow.setWindowTitle(_translate("TradingSuggestStockWindow", "股票交易-股票列表"))
        item = self.tableWidgetBacktest.horizontalHeaderItem(0)
        item.setText(_translate("TradingSuggestStockWindow", "股票名称"))
        item = self.tableWidgetBacktest.horizontalHeaderItem(1)
        item.setText(_translate("TradingSuggestStockWindow", "股票代码"))
        item = self.tableWidgetBacktest.horizontalHeaderItem(2)
        item.setText(_translate("TradingSuggestStockWindow", "当前股价"))
        item = self.tableWidgetBacktest.horizontalHeaderItem(3)
        item.setText(_translate("TradingSuggestStockWindow", "开盘价"))
        item = self.tableWidgetBacktest.horizontalHeaderItem(4)
        item.setText(_translate("TradingSuggestStockWindow", "最高价"))
        item = self.tableWidgetBacktest.horizontalHeaderItem(5)
        item.setText(_translate("TradingSuggestStockWindow", "最低价"))
        # item = self.tableWidgetBacktest.horizontalHeaderItem(6)
        # item.setText(_translate("TradingSuggestStockWindow", "换手率"))

        # item = self.tableWidgetBaseInfo.horizontalHeaderItem(7)
        # item.setText(_translate("TradingStockBacktestWindow", "总分"))
        self.label_2.setText(_translate("TradingSuggestStockWindow", "股票基本信息"))
        self.rbtn1.setText(_translate("TradingSuggestStockWindow", "自选股票"))
        self.rbtn2.setText(_translate("TradingSuggestStockWindow", "策略一推荐股票"))
        self.rbtn3.setText(_translate("TradingSuggestStockWindow", "策略二推荐股票"))
        self.pushButtonReturn.setText(_translate("TradingSuggestStockWindow","返回主界面"))